Steps to follow to generate config file in k8s

1. Generate or Obtain the Kubeconfig File
If you already have a kubeconfig file for your cluster (usually located at ~/.kube/config), you can copy it to your working directory.
If you don't have one, generate it using the following command:
bash
Copy code
kubectl config view --raw > cronjob-kubeconfig.yaml
This command outputs your current Kubernetes configuration, including authentication credentials.
